version: '3.8'
services:
  pmc-ecm-store:
    image: pmc-ecm-store-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/pmc-ecm-store
      - /pmc-ecm-store/node_modules
      - /pmc-ecm-store/.husky
      - /pmc-ecm-store/.vscode
