import { SWRProvider } from './swr-provider';
import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const iCielVAGRoundedNext = localFont({
  src: [
    {
      path: '../fonts/iCielVAGRoundedNext-ExtraLight.otf',
      weight: '200',
    },
    {
      path: '../fonts/iCielVAGRoundedNext-Light.otf',
      weight: '300',
    },
    {
      path: '../fonts/iCielVAGRoundedNext-Regular.otf',
      weight: '400',
    },
    {
      path: '../fonts/iCielVAGRoundedNext-Medium.otf',
      weight: '500',
    },
    {
      path: '../fonts/iCielVAGRoundedNext-DemiBold.otf',
      weight: '600',
    },
    {
      path: '../fonts/iCielVAGRoundedNext-Bold.otf',
      weight: '700',
    },
  ],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SWRProvider>
      <html lang="en" className={iCielVAGRoundedNext.className}>
        <body>
          <main>{children}</main>
        </body>
      </html>
    </SWRProvider>
  );
}
